<?php if($block->getData('widgettitle')): ?>
            <div class="block-title-main">
                <h2><?php echo $block->getData('widgettitle'); ?></h2>
                <div class="title-border"></div>
            </div>
<?php endif; ?>
<div class="hpb-main hpb-slider">
<?php
        $url = "https://vnexpress.net/rss/tin-moi-nhat.rss";
        if(isset($_POST['submit'])){
            if($_POST['feedurl'] != ''){
                $url = $_POST['feedurl'];
            }
        }

        $invalidurl = false;
        if(@simplexml_load_file($url)){
            $feeds = simplexml_load_file($url);
        }else{
            $invalidurl = true;
            echo "<h2>Invalid RSS feed URL.</h2>";
        }


        $i=0;
        if(!empty($feeds)){

            $site = $feeds->channel->title;
            $sitelink = $feeds->channel->link;

            ?>
                <?php
                foreach ($feeds->channel->item as $item) {

                    $title = $item->title;
                    $link = $item->link;
                    $description = $item->description;
                    $postDate = $item->pubDate;
                    $pubDate = date('D, d M Y',strtotime($postDate));


                    if($i>=20) break;
                    ?>
                    <div class="hpb-inner">
                    <div class="post" style="max-width:300px; margin: auto">
                    
                        <div class="post-head">
                        <h2><a class="feed_title" href="<?php echo $link; ?>" style="font-weight:bold; font-size:22px"><?php echo $title; ?></a></h2>
                        <span><?php echo $pubDate; ?></span>
                        </div>
                        <div class="post-content">
                        <?php echo implode(' ', array_slice(explode(' ', $description), 0, 20)) . "..."; ?> <a href="<?php echo $link; ?>">Read more</a>
                        </div>
                    </div>
                    </div>

                    <?php
                    $i++;
                    
                }
        }else{
        if(!$invalidurl){
            echo "<h2>No item found</h2>";
        }
        }
?>
</div>