<div style="margin-bottom:4px;padding:4px;border: 2px solid #f2703e">
            <?php
                $access_key = "&appid=fbd57cf751f7ad6f3304fcb8559374e1";
                $country = "Vietnam";
                $region = "Hanoi";
            
                $current_obj = $block->getCurrentData($region, $country, $access_key);
                $city_id = $current_obj->id;
                $forcast_obj = $block->getForcast($city_id, $access_key);
            ?>
            <div >
                <div >
                    <div>Thành phố: <?php echo $region.", ".$country ?></div>
                    <div>Thời gian cập nhật: <?php echo date("d/m/Y H:i:s",$current_obj->dt); ?></div>
                </div>
                <div>
                    <div>
                        <div style="height:50px; width:50px; margin-left:auto;margin-right:auto;
                             background: url('http://openweathermap.org/img/w/<?php echo $current_obj->weather[0]->icon ?>.png');background-size: cover;"></div>
                        <div><?php echo $current_obj->main->temp." &#8451;" ?> - <?php echo  $current_obj->weather[0]->main ?></div>
                        <div>Mây: <?php echo $current_obj->clouds->all."%" ?></div>
                    </div>
                    <div>
                        <div>Pressure: <?php echo $current_obj->main->pressure."hPa" ?></div>
                        <div>Độ ẩm: <?php echo $current_obj->main->humidity."%" ?></div>
                        <div>Nhiệt độ thấp nhất: <?php echo $current_obj->main->temp_min." &#8451;" ?></div>
                        <div>Nhiệt độ cao nhất: <?php echo $current_obj->main->temp_max." &#8451;" ?></div>
                    </div>
                </div>
                <div>
                    <div>Tốc độ gió: <?php echo $current_obj->wind->speed." meter/sec" ?></div>
                    <div>Hướng gió: <?php echo $current_obj->wind->deg."&deg;" ?></div>
                </div>
            </div>
            <div class="hpb-main hpb-slider">
                    <?php 
                        $forcast_list = $forcast_obj->list;
                        foreach($forcast_list as $temp){ 
                            if(date("d/m",$current_obj->dt) == date("d/m",$temp->dt)) {?>
                <div class="hpb-inner" style="border: 1px solid;">
                    <div><b><?php echo date("d/m H:i",$temp->dt) ?></b></div>
                        <div style="height:50px; width:50px; margin-left:auto;margin-right:auto;
                             background: url('http://openweathermap.org/img/w/<?php echo $temp->weather[0]->icon ?>.png') no-repeat;"></div>
                             <div><?php echo $temp->main->temp." &#8451;" ?></div>
                             <div><?php echo $temp->main->humidity."%" ?></div>
                             <div><?php echo $temp->weather[0]->main ?></div>
                        </div>
                            <?php } }
                        ?>
                    </div>
                </div>
            </div>
</div>